### ISSUE TITLE
block duplicate fill

### ISSUE THREAD

**Issue by Jonathan-devs** [Hiroshji/PyQT6-Tetris#5]
When i place down blocks, the blocks are not placed properly, and will semingly fill inn.
![image](https://github.com/user-attachments/assets/07e1564f-c97e-4d57-844a-9c22d85534ac)

**Comment by Hiroshji** [comment]
I Found the issue where the blocks duplicate after earing 29 points.
the issue was due to the clear_lines function's line-clearing. Specifically, the line:

```python
self.board = [[0] * BOARD_WIDTH] * cleared_lines + new_board
```

(Solution)
```python
self.board = [[0] * BOARD_WIDTH for _ in range(cleared_lines)] + new_board
```
Made it so that each row is uniqe
This makes sure that each row in the cleared section is a distinct list, preventing the duplication.

(the updated part of the code that handles new lines)
```python
def clear_lines(self):
    new_board = [row for row in self.board if any(cell == 0 for cell in row)]
    cleared_lines = BOARD_HEIGHT - len(new_board)
    if cleared_lines > 0:
        self.score += cleared_lines ** 2  # Simple scoring
        self.score_changed.emit(self.score)  # Emit the score change signal
        self.board = [[0] * BOARD_WIDTH for _ in range(cleared_lines)] + new_board
    self.update()
```
